# image will be published to ghcr.io/<user>/<name>
name: leloublue
# description will be included in the image's metadata
description: My custom UBlue Image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-framework
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: parts/system.yml
  - from-file: parts/desktop.yml
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

